---
wandb:
  project: "vit-scratch"

data:
  train_dir: "./data/tiny-imagenet-200/train"
  val_dir: "./data/tiny-imagenet-200/val"
  image_size: 128
  normalization_mean: [0.485, 0.456, 0.406]
  normalization_std: [0.229, 0.224, 0.225]
  random_resized_crop_scale: [0.8, 1.0]
  random_horizontal_flip_p: 0.5
  use_randaugment: true
  randaugment_num_ops: 2
  randaugment_magnitude: 9
  use_random_erasing: true
  random_erasing_p: 0.25

train:
  output_dir: "./outputs/checkpoints/layernorm-tanh"
  # resume_from_checkpoint: "./checkpoint_path.pth"
  checkpoint_every_x_epochs: 50
  device: "cuda"
  num_workers: 4
  batch_size: 256
  epochs: 500
  warmup_epochs: 10
  lr: 3.0e-4
  mixup:
    mixup_alpha: 0.8
    cutmix_alpha: 1.0
    prob: 1.0
    switch_prob: 0.5
    label_smoothing: 0.1
  
model:
  patch_size: 16
  in_channels: 3
  num_classes: 200
  embed_dim: 768
  depth: 6
  num_heads: 4
  dropout: 0.1
  attention_dropout: 0.1
  norm_layer: "layernorm"
