---
wandb:
  project: "movingmnist"

train:
  output_dir: "./outputs/checkpoints/movingmnist"
  # resume_from_checkpoint: "./checkpoint_path.pth"
  checkpoint_every_x_epochs: 25
  device: "cuda"
  num_workers: 4
  batch_size: 32
  epochs: 100
  warmup_epochs: 10
  lr: 1.0e-3
  
model:
  architecture: "unet3d"
  in_channels: 1
  num_classes: 1
  up: "conv"
  residual_blocks: true
  dropout: 0.2
  features:
    - 64
    - 128
    - 256
    - 512
